---
services:
  i2pd:
    container_name: i2pd
    image: chrisbensch/docker-i2pd:simplified
    network_mode: host
    volumes:
      - ./i2pd-torseed.conf:/var/lib/i2pd/i2pd.conf
      - ./appdata/var/lib/i2pd/:/var/lib/i2pd/
    restart: always
