version: '3.3'
services:
  i2p:
    container_name: i2p-tor
    image: 'divax/i2p:i2p-tor'
    environment:
      - PORT_TOR=9950
      - PORT_HTTP_PROXY=4544
      - ENABLE_HTTPPROXY=1
    ports:
      - '7070:7070'
      - '4544:4444'
      - '9950:9050'
## Adding a dedicated volume like this breaks i2p completely
#    volumes:
#      - '/data/docker-i2p-tor/data:/home/i2pd/data'
